#!/bin/bash

echo "🔧 AWS CLI Commands to Fix Lambda IAM Permissions"
echo "=================================================="
echo ""
echo "Run these commands with appropriate AWS permissions:"
echo ""

echo "# 1. Attach S3 Full Access Policy to Lambda Role"
echo "aws iam attach-role-policy \\"
echo "  --role-name download-generator-role-hn3e1qhh \\"
echo "  --policy-arn arn:aws:iam::aws:policy/AmazonS3FullAccess"
echo ""

echo "# 2. Or create a custom inline policy (more secure)"
echo "aws iam put-role-policy \\"
echo "  --role-name download-generator-role-hn3e1qhh \\"
echo "  --policy-name LambdaS3Access \\"
echo "  --policy-document '{"
echo "    \"Version\": \"2012-10-17\","
echo "    \"Statement\": ["
echo "      {"
echo "        \"Effect\": \"Allow\","
echo "        \"Action\": ["
echo "          \"s3:GetObject\","
echo "          \"s3:PutObject\","
echo "          \"s3:ListBucket\""
echo "        ],"
echo "        \"Resource\": ["
echo "          \"arn:aws:s3:::mvp-labeler-storage\","
echo "          \"arn:aws:s3:::mvp-labeler-storage/*\""
echo "        ]"
echo "      }"
echo "    ]"
echo "  }'"
echo ""

echo "# 3. Test the function after fixing permissions"
echo "aws lambda invoke \\"
echo "  --function-name download-generator \\"
echo "  --payload fileb://test-payload-final.json \\"
echo "  response-test.json \\"
echo "  --region eu-west-2"
echo ""

echo "# 4. Check the response"
echo "cat response-test.json"
echo ""

echo "🎯 Alternative: Use AWS Console"
echo "=============================="
echo "1. Go to AWS Lambda Console"
echo "2. Find function: download-generator"
echo "3. Click Configuration → Permissions"
echo "4. Click the execution role name"
echo "5. Click Add permissions → Attach policies"
echo "6. Search for: AmazonS3FullAccess"
echo "7. Select and click Add permissions"
echo ""

echo "✅ After fixing permissions, your Lambda function will work!" 